ТЗ-13. first try
Ermakrm/java-shareit pull request #1
Opened 2023-05-15 18:34 UTC by Ermakrm

2023-05-16 18:59 UTC, z8q requested changes

2023-05-16 18:59 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> search(@RequestParam String text, @RequestHeader("X-Sharer-User-Id") Long userId) {
Если есть перспектива в дальнейшем использовать userId, то можно оставить. Либо все таки использовать)

2023-05-16 18:59 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto createUser(@Valid @RequestBody UserDto user) {
Когда создаем User или Item без какого-нибудь обязательного поля, можно было бы возвращать соответствующую ошибку.
Сейчас приходит:
{
	"timestamp": "2023-05-16T18:46:55.431+00:00",
	"status": 400,
	"error": "Bad Request",
	"path": "/users"
}

если email уберем или name у пользователя

2023-05-17 13:35 UTC, Ermakrm commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public List<ItemDto> search(@RequestParam String text, @RequestHeader("X-Sharer-User-Id") Long userId) {
Не знаю, может и есть) Но по ТЗ X-Sharer-User-Id приходит в каждом запросе

2023-05-17 13:36 UTC, Ermakrm commented on src/main/java/ru/practicum/shareit/user/UserController.java
> +    public UserDto createUser(@Valid @RequestBody UserDto user) {
поправил

2023-05-17 14:07 UTC, Ermakrm commented
Привет! Уже после повторной отправки увидел комментарий, оставленный на ЯП. Спасибо за инфу! Менять уже не стал, т.к. в следующем спринте всё это и так нужно будет удалять)

2023-05-18 13:56 UTC, z8q approved these changes

2023-05-23 17:44 UTC, merged