ТЗ-14
Ermakrm/java-shareit pull request #2
Opened 2023-06-06 13:22 UTC by Ermakrm

2023-06-06 21:14 UTC, z8q requested changes

2023-06-06 21:14 UTC, z8q commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS requests
Эту таблицу только в 15-м дз будем использовать

2023-06-06 21:14 UTC, z8q commented on src/main/java/ru/practicum/shareit/item/ItemController.java
> +    public ItemResponseDto getItem(@PathVariable Long itemId, @RequestHeader(USER_ID) Long userId) {
Из ТЗ:
`Теперь нужно, чтобы владелец видел даты последнего и ближайшего следующего бронирования для каждой вещи, когда просматривает список (GET /items).`
Нужно добавить даты.
Сейчас так приходит:
[
	{
		"id": 1,
		"name": "car",
		"description": "Tesla",
		"available": true,
		"lastBooking": null,
		"nextBooking": {
			"id": 1,
			"bookerId": 2
		},
		"comments": []
	},
	{
		"id": 2,
		"name": "car",
		"description": "Tesla",
		"available": true,
		"lastBooking": {
			"id": 4,
			"bookerId": 2
		},
		"nextBooking": null,
		"comments": []
	}
]

2023-06-06 21:14 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/dto/UserDto.java
> +    @NotNull
NotBlank проверяет поле на null тоже

2023-06-06 21:14 UTC, z8q commented on src/main/java/ru/practicum/shareit/user/service/UserServiceImpl.java
> +                .orElseThrow(() -> new UserNotFoundException("User not found"));
Если сделать запрос по несуществующему пользователю:
GET http://localhost:8080/users/8
В логах отображается сообщение "User not found"
А в возвращаемом объекте только так:
{
	"timestamp": "2023-06-06T21:07:11.032+00:00",
	"status": 404,
	"error": "Not Found",
	"path": "/users/8"
}

Тут в целом понятно, что не найдено. Но есть запросы, где много параметров, например:
POST http://localhost:8080/bookings
тут можно указать несуществующий "itemId", либо X-Sharer-User-Id. Придет все равно:
{
	"timestamp": "2023-06-06T21:11:19.019+00:00",
	"status": 404,
	"error": "Not Found",
	"path": "/bookings"
}
Без уточнений для пользователя. Хотя в логах приложения сообщение отображается верно.

Можно этот момент тоже посмотреть

2023-06-07 13:14 UTC, Ermakrm commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS requests
Она была в "советах от ментора", поэтому решил сразу добавить

2023-06-07 13:14 UTC, Ermakrm commented
Привет, всё поправил, спасибо!

2023-06-07 22:59 UTC, z8q approved these changes

2023-06-07 23:01 UTC, merged