ТЗ-15
Ermakrm/java-shareit pull request #3
Opened 2023-06-24 01:27 UTC by Ermakrm

2023-06-26 22:03 UTC, z8q requested changes

2023-06-26 22:03 UTC, z8q commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +        return service.findByUserId(userId);
В тз написано:
Запросы должны возвращаться в отсортированном порядке **от более новых** к более старым.
Попробовал запросить, получается так:
```
[
	{
		"id": 1,
		"description": "something1",
		"created": "2023-06-27T00:05:55.373633",
		"items": [
			{
				"id": 2,
				"name": "car",
				"description": "Tesla",
				"available": true,
				"lastBooking": null,
				"nextBooking": null,
				"comments": null,
				"requestId": 1
			}
		]
	},
	{
		"id": 2,
		"description": "something2",
		"created": "2023-06-27T00:06:48.700414",
		"items": [
			{
				"id": 3,
				"name": "car",
				"description": "Tesla",
				"available": true,
				"lastBooking": null,
				"nextBooking": null,
				"comments": null,
				"requestId": 2
			}
		]
	},
	{
		"id": 3,
		"description": "something3",
		"created": "2023-06-27T00:09:07.479887",
		"items": [
			{
				"id": 4,
				"name": "car",
				"description": "Tesla",
				"available": true,
				"lastBooking": null,
				"nextBooking": null,
				"comments": null,
				"requestId": 3
			}
		]
	}
]
```

Получаем первым самый старый, внизу самый новый, то есть реализовано наоборот

2023-06-26 22:03 UTC, z8q commented on src/main/java/ru/practicum/shareit/request/ItemRequestController.java
> +    public List<ItemRequestResponseDto> findAllWithPagination(
тут тоже порядок не совсем как по тз

2023-06-27 06:54 UTC, Ermakrm commented
Привет! Добавил сортировку

2023-06-27 21:01 UTC, z8q approved these changes

2023-06-27 21:18 UTC, merged