ТЗ-16
Ermakrm/java-shareit pull request #4
Opened 2023-07-07 22:26 UTC by Ermakrm

2023-07-09 09:42 UTC, z8q requested changes

2023-07-09 09:42 UTC, z8q commented on pom1.xml
> +<?xml version="1.0" encoding="UTF-8"?>
для чего pom1?

2023-07-09 09:42 UTC, z8q commented on pom.xml
>  		<dependency>
зависимости в строках 32-69 помечены как duplicated
Если они нужны в gateway или в server, стоит только там и оставить
В основной пом обычно выводят dependancyManagement и в properties указывают все версии зависимостей, которые применяются в проекте

2023-07-09 09:42 UTC, z8q commented on server/src/main/resources/application.properties
> +server.port=9090
в интерфейсах-мапперах надо убрать аннотацию `@Component`
в джава-доке `@Mapper` есть такая информация, где видим, что Component будет генерироваться
```
// we have CarMapper
  @Mapper(
       componentModel = MappingConstants.ComponentModel.SPRING,
       uses = MarkMapper.class,
       injectionStrategy = InjectionStrategy.CONSTRUCTOR)
  public interface CarMapper {
      @Mapping(target = "name", source = "mark")
      CarDto convertMap(CarEntity carEntity);
  }
  
  // generates
  @Component
  public class CarMapperImpl implements CarMapper {
      private final MarkMapper markMapper;
      @Autowired
      public CarMapperImpl(MarkMapper markMapper) {
          this.markMapper = markMapper;
      }
      @Override
      public CarDto convertMap(CarEntity carEntity) {
          if ( carEntity == null ) {
              return null;
          }
          CarDto carDto = new CarDto();
          carDto.setName( markMapper.mapMark( carEntity.getMark() ) );
          return carDto;
      }
  }
```

2023-07-09 11:22 UTC, Ermakrm commented on pom1.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Сохранял себе на всякий случай, забыл удалить)

2023-07-09 11:22 UTC, Ermakrm commented on pom.xml
>  		<dependency>
Поправил

2023-07-09 11:22 UTC, Ermakrm commented on server/src/main/resources/application.properties
> +server.port=9090
Поправил

2023-07-10 03:00 UTC, z8q approved these changes

2023-07-10 03:25 UTC, merged